[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ha-zaptec"
version = "0.8.7"
description = "Home Assistant integration for Zaptec EV smart chargers"
authors = [
    { name = "Svein Seldal", email = "sveinse@seldal.com" },
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyzaptec==0.8.7",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-cov",
    "mypy",
    "ruff==0.15.22",
    "homeassistant>=2024.4.3",
    "colorlog>=6.10.1",
]

[project.urls]
Repository = "https://github.com/ha-zaptec-community/ha-zaptec.git"
GitHub = "https://github.com/ha-zaptec-community/ha-zaptec"

[tool.hatch.build.targets.wheel]
packages = ["custom_components/zaptec"]

[tool.uv]
python-preference = "system"

[tool.uv.workspace]
members = [
    "pyzaptec",
]

[tool.uv.sources]
pyzaptec = { workspace = true, editable = true }

[tool.pytest.ini_options]
pythonpath = [
    ".",
]
testpaths = [
    "tests",
]
log_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(name)s:%(filename)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = [
    "ignore::DeprecationWarning",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
relative_files = true
branch = true
source = [
    "custom_components/zaptec",
]

[tool.coverage.report]
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",
  # Don't complain about missing debug-only code:
  "def __repr__",
  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",
  # TYPE_CHECKING and @overload blocks are never executed during pytest run
  "if TYPE_CHECKING:",
  "@overload",
]

[tool.mypy]
mypy_path = [
    "custom_components",
]
strict = false
exclude_gitignore = true
show_column_numbers = true
show_error_codes = true

[tool.ruff]
# The contents of this section is based on
# https://github.com/home-assistant/core/blob/dev/pyproject.toml
required-version = "==0.15.22"
target-version = "py314"
line-length = 98

[tool.ruff.lint]
select = [
    "ALL",
]

# Here we specify the rules we want to ignore. Its fully possible to add more
# rules here if necessary. If in doubt, please check the Home Assistant
# rule list. If they use excepmt for a rule, we should use it too.
#   https://github.com/home-assistant/core/blob/dev/pyproject.toml#L652
ignore = [
    "ARG001", # unused-argument - generic callbacks and setup methods create a lot of warnings (from tool.pylint."MESSAGES CONTROL")
    "ARG002", # Same as above
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "BLE001", # Do not catch blind exception: `Exception` (from broad-except in tool.pylint."MESSAGES CONTROL")
    "COM812", # incompatible with formatter
    "D202",   # No blank lines allowed after function docstring
    "D203",   # no-blank-line-before-class (incompatible with formatter)
    "D212",   # multi-line-summary-first-line (incompatible with formatter)
    "D213",   # Multi-line docstring summary should start at the second line
    "E501",   # line too long
    "ISC001", # incompatible with formatter

    "PLR0911", # Too many return statements ({returns} > {max_returns})
    "PLR0912", # Too many branches ({branches} > {max_branches})
    "PLR0913", # Too many arguments to function call ({c_args} > {max_args})
    "PLR0915", # Too many statements ({statements} > {max_statements})

    # Moving imports into type-checking blocks can mess with pytest.patch()
    "TC001", # Move application import {} into a type-checking block
    "TC002", # Move third-party import {} into a type-checking block
    "TC003", # Move standard library import {} into a type-checking block
    # Quotes for typing.cast generally not necessary, only for performance critical paths
    "TC006", # Add quotes to type expression in typing.cast()

    "TRY003", # Avoid specifying long messages outside the exception class
    "TRY400", # Use `logging.exception` instead of `logging.error`

    # definitely skipped in HA, not obvious how
    "EM101",  # Exception must not use a string literal, assign to variable first
    "EM102",  # Exception must not use an f-string literal, assign to variable first
    "FBT001", # Boolean-typed positional argument in function definition
    "FBT002", # Boolean default positional argument in function definition
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",  # Allow assert in tests
    "INP001",  # Don't complain over missing __init__.py in test dirs
]
"scripts/*" = [
    "D103",  # Don't complain over missing docstrings in scripts
    "T201",  # Allow for scripts to write to stdout
]

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.pydocstyle]
convention = "google"
property-decorators = ["propcache.api.cached_property"]
