#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# If pyzaptec is present, we skip installing it from pip, since we want to use
# the local version.
if [[ -d "${PWD}/pyzaptec" ]]; then
    suffix="--skip-pip-packages pyzaptec"
else
    suffix=""
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/integration_blueprint
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
set -x
hass --config "${PWD}/config" --debug ${suffix}
