#!/usr/bin/env bash

set -ex

cd "$(dirname "$0")/.."

# Fix ownership of the mounted volume using sudo
if [ "${REMOTE_CONTAINERS}" = "true" ] || [ "${CODESPACES}" = "true" ]; then
    sudo chown -R vscode:vscode /home/vscode/.cache/uv
fi

uv sync --all-extras

# If the pyzaptec directory exists, add it as an editable package
if [[ -d "pyzaptec" ]]; then
    uv add --editable ./pyzaptec
fi
